import { ExperienceCardProps } from '@pages/Resume/components/ExperienceCard';

export const roles: ExperienceCardProps[] = [
    {
        title: 'UX Design Engineer',
        company: 'Toyota North America',
        startDate: '2025',
        endDate: 'Present',
        location: 'Hybrid - Plano, TX',
        callout: '',
        theme: '',
        logo: 'toyota',
    },
    {
        title: 'Staff UI/UX Designer',
        company: 'ServiceNow',
        startDate: '2024',
        endDate: '2025',
        location: 'Remote',
        callout: 'Shaping internal platforms and AI tooling to support workflows for sales, comms, and IT.',
        theme: 'primary',
        logo: 'servicenow',
    },
    {
        title: 'Senior Product Designer',
        company: 'Albertsons',
        startDate: '2023',
        endDate: '',
        location: 'Remote',
        callout: '',
        theme: '',
        logo: 'albertsons',
    },
    {
        title: 'Senior Product Designer',
        company: 'ActBlue',
        startDate: '2022',
        endDate: '2023',
        location: 'Remote',
        callout: 'Connected big tools to little tools. Reduced total support costs by $1.5M annually.',
        theme: 'secondary',
        logo: 'actblue',
    },
    {
        title: 'Senior Product Designer',
        company: 'Routable',
        startDate: '2023',
        endDate: '',
        location: 'Remote',
        callout: '',
        theme: '',
        logo: 'routable',
    },
    {
        title: 'Senior Product Designer',
        company: 'FireHydrant',
        startDate: '2020',
        endDate: '2021',
        location: 'Remote',
        callout: '',
        logo: 'firehydrant',
    },
    {
        title: 'UX Designer',
        company: 'Indeed',
        startDate: '2020',
        endDate: '',
        location: 'Remote',
        callout: '',
        logo: 'indeed',
    },
    {
        title: 'Senior UX Engineer',
        company: 'Visa',
        startDate: '2017',
        endDate: '2020',
        location: 'Austin, TX',
        callout: 'Reinvented enterprise omnichannel software for fraud, analytics, and transaction tokenization.',
        logo: 'visa',
    },
    {
        title: 'UX Engineer',
        company: 'Visa',
        startDate: '2015',
        endDate: '2017',
        location: 'Austin, TX',
        callout: 'Crafted, built, and implemented a new framework library serving hundreds of developers globally.',
        logo: 'visa',
    },
];